### ISSUE TITLE
Custom log file path

### ISSUE THREAD

**Issue by skinsoft** [dbmdz/iiif-server-hymir#1]
Hello,

Hymir server is using this path ``/var/log/iiif/iiifServer.log`` to store its logs but I have restricted rights on the server and I cannot access to ``/var/log``.

Could it be possible to configure the log file path ?

Note : As a workaround I've changed the logback config from ``<file>/var/log/iiif/iiifServer.log</file>`` to ``<file>${IIIF_SERVER_LOG_DIR}/iiifServer.log</file>`` and it works. Do you want me to provide a PR ?

**Comment by datazuul** [comment]
Thank you for your issue. I made the logfile path now configurable through environment variable but providing also a default value. See the new logging section in the README.md.

By the way: if you are using Hymir in production we would love to add your project to the "Users" section in the README.
