### ISSUE TITLE
Error in manifest file should not lead to a 404

### ISSUE THREAD

**Issue by VonUniGE** [dbmdz/iiif-server-hymir#10]
If a manifest file contains an error, the request `iiif/presentation/v2/1234567890/manifest` return a 404.

Step to reproduce:

   - Edit one of your manifest file
   - Change "@type": "dctypes:Image" to "@type": "dctypes:Illustration"
   - Get the manifest iiif/presentation/v2/1234567890/manifest
   - Observe that a 404 is returned 

Desired behavior:
A more meaningful HTTP error should be returned such as 422  (Unprocessable Entity)

**Comment by datazuul** [comment]
we will throw an internal error 500 (and log error message).
422 is not applicable as it is a client error (unprocessable request content), see https://tools.ietf.org/html/rfc4918#page-78
will be part of upcoming 4.0.0 release
