### ISSUE TITLE
Prometheus endpoint ?

### ISSUE THREAD

**Issue by MarcAgate** [dbmdz/iiif-server-hymir#108]
I can't monitor Hymir with prometheus (and grafana) as the endpoint server:port/actuator/prometheus is not available (or activated), even though "micrometer-registry-prometheus" lib is integrated.
How can I monitor hymir with prometheus ?

**Comment by jbaiter** [comment]
Try `server:port/monitoring/prometheus` or change the [management base path in the `application.yml`](https://github.com/dbmdz/iiif-server-hymir/blob/master/src/main/resources/application.yml#L40).

**Comment by MarcAgate** [comment]
Thanks! That worked.
