### ISSUE TITLE
There is a need to update api versions

### ISSUE THREAD

**Issue by MarcAgate** [dbmdz/iiif-server-hymir#14]
iiif-apis version should be changed in pom.xml from 0.3.1 to 0.3.2 (that fixes an issue related to tiff format) and iiif-server-hymir should be upgraded in maven repo.
Thx

**Comment by morpheus-87** [comment]
I just released a new version `3.5.2`, which includes an update of the `iiif-apis` to `0.3.2`. Should be available in the maven repo in the next hours.

**Comment by MarcAgate** [comment]
Thanks for that !
