### ISSUE TITLE
Redirection to canonical url is not optional

### ISSUE THREAD

**Issue by MarcAgate** [dbmdz/iiif-server-hymir#15]
I have noticed that this redirection ( https://github.com/dbmdz/iiif-server-hymir/blob/master/src/main/java/de/digitalcollections/iiif/hymir/image/frontend/IIIFImageApiController.java#L113 ) is mandatory in Hymir code while the specs says: 

Image servers MAY redirect the client to the canonical URI from a non-canonical equivalent.
see http://iiif.io/api/image/2.0/#canonical-uri-syntax

it would be great to be able to choose using redirection or not.

**Comment by jbaiter** [comment]
This is now implemented on the master branch, just set this value in your `application.yml`:

```yml
custom:
  iiif:
    image:
      canonicalRedirect: false
```

**Comment by MarcAgate** [comment]
Great ! Thank you. Since we reference hymir server (v. 3.5.2) in our pom,  could you update maven repo as well ?

**Comment by jbaiter** [comment]
@datazuul @morpheus-87 can you guys release 3.6.0? I don't have the signing keys on my laptop :-/
