### ISSUE TITLE
How to load images from disk

### ISSUE THREAD

**Issue by roberts-g** [dbmdz/iiif-server-hymir#2]
Hi, sorry if this is a dumb question, but I cannot seem to work out how to display any images. I have tried using "file:/path/to/image.jp2" under "View image with OpenSeadragon", but that doesn't seem to work.

Apologies again if this is really obvious.

**Comment by roberts-g** [comment]
I should probably add that, when I try doing that, I get the following error message:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sat Oct 14 17:38:50 BST 2017
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by morpheus-87** [comment]
You have to define a yaml file, which describes the resolving rules from identifier to paths, see here: <https://github.com/dbmdz/iiif-server-hymir#image-and-presentation-manifest-resolving>

Besides, you have to configure the server to use your rules by running `java -jar hymir-3.0.1-exec.jar --spring.profiles.active=local --rules=<path to your rules file>`

**Comment by roberts-g** [comment]
So I have tried doing that, but the identifier still can't be resolved.
This is the command I am running:
`java -jar hymir-3.0.1-exec.jar --spring.profiles.active=local --rules=file:/home/robert/Downloads/rules.yml
`

and this is the rules.yml I am using:
` - pattern: ^(.*)$
   substitutions:
       - 'file:/home/robert/Documents/Images/$1'`

I try to put image1.jp2 as the identifier, however the log says that image1.jp2 is not resolvable

I then

**Comment by datazuul** [comment]
you are too fast ;-).
Yes, you are right, in our current download this does not work. therefore we will provide a new release, that will be available in the next days. meanwhile you could build the JAR-packages from the current code. this is proven to work.

Another comment: as you can see from our compatibility list, we are not yet supporting JPEG2000 (jp2-files) due license restrictions for required libraries. but we will investigate in an openjpeg-integration to support this in the future.

**Comment by morpheus-87** [comment]
We released a new version `3.1.0` yesterday - please try it again and tell us, if it works now. But keep in mind, that JPEG2000 is not supported at the moment.

**Comment by tyy0402** [comment]
I also met this problem. The version of hymir is 3.3.0. After I made rules.yml, I could not View image with OpenSeadragon.
Unable to open[object Object]:HTTP 404 Attempting to load TileSource.

And I tried to open the URL on my browser ,http://120.76.144.46:9000/image/v2/image_001/full/full/0/default.jpg
HTTP ERROR 404 

I use a cloud server（Ubuntu）

**Comment by morpheus-87** [comment]
Thank you for the feedback. Could you please provide us the `rules.yml` you are using?

**Comment by jbaiter** [comment]
Can you provide more information?

- What do your resolving rules look like?
- What does your file system look like?
- What is the format of the source images?
- Can you run the application with `--debug` and upload the log somewhere?

**Comment by tyy0402** [comment]
- rules.yml：
`- pattern: ^(.*)$`
  `substitutions:`
    `- 'file:/home/hans/my_images/$1'`

- Sorry, I don't understand what the file system means.

- format:jpg

- I run `java -jar hymir-3.3.0-exec.jar --spring.profiles.active = local`but I cannot open the web page

PS: I didn't install tomcat, is it necessary?

**Comment by jbaiter** [comment]
You have to include the file extension in your substitution pattern. With your current setup it will resolve `image_001` to `/home/hans/my_images/image_0001`.
Even if the file existed, the resolving mechanism has no way to tell whether it's an image without looking at the header (which isn't implemented and not likely to be in the future, due to performance reasons).

Suggested solution: Change `$1` to `$1.jpg` in your substitution pattern.

Also, Tomcat is embedded in the JAR, you don't need a dedicated application server :-)

**Comment by jbaiter** [comment]
- Can you please post your complete **actual** `rules.yml` file, including indentation? The way you posted it the indentation is not clear, this stuff matters with YAML
- Please run with `--debug` and check the logs, are there any hints on what is going wrong?
- What does "it doesn't work" mean, precisely? You access http://120.76.144.46:9000/image/v2/image_001/full/full/0/default.jpg and get a 404 response?

**Comment by tyy0402** [comment]
- The rules:
```
- pattern: ^(.*)$
  substitutions:
    - 'file:/home/tyy/IIIF/$1.jpg'
```

- I tried it again, It works!!!!!!! I don't know why since I changed nothing. While, it better than doesn't work. LOL
Thanks so much!

**Comment by jbaiter** [comment]
For Mirador, you need a [IIIF Presentation API Manifest](http://iiif.io/api/presentation/2.0/#manifest).
