### ISSUE TITLE
Help building please

### ISSUE THREAD

**Issue by pdiveris** [dbmdz/iiif-server-hymir#20]
Hi there, this isn't really an issue as such. Could you please help me by pointing at the command I need to run to build from source? I've installed maven etc.. please tolerate my ignorance and feel free to close this bit I would appreciate your help!

**Comment by datazuul** [comment]
I added a development section in README (https://github.com/dbmdz/iiif-server-hymir#development)

**Comment by pdiveris** [comment]
Thank you!

**Comment by pdiveris** [comment]
Hi, sorry to bother you but the build fails in the tests. I am trying to figure out exactly wgere but you may have an idea already.

<img width="1242" alt="screen shot 2018-07-25 at 12 09 43" src="https://user-images.githubusercontent.com/1022373/43197628-a7282f9c-9003-11e8-9afa-5421999b45bd.png">

**Comment by pdiveris** [comment]
I am working on a mac at this moment and installing libturbojpeg from the binaries doesn't seem to resolve it. I do get a binary if I comment most tests out, which is obviously not desirable. I don't mind compiling on Debian but it'll have to wait until I get back home. Will confirm asap.

**Comment by datazuul** [comment]
To build without tests, execute:

```sh
$ mvn clean install -DskipTests=true
```

**Comment by pdiveris** [comment]
That worked, thank you. Forgive my java/maven ignorance..
