### ISSUE TITLE
Manifests and collections

### ISSUE THREAD

**Issue by pdiveris** [dbmdz/iiif-server-hymir#21]
Hi there, 

I understand now that one needs to implement them, thank you. Couple of things though

* If I request http://localhost:9000/presentation/v2/collection/tash.jpg (which is an existing jpg) I get a page can't be found. On the console I do not get a message such as 

```      
LOGGER.info("Could not retrieve collection {}", collectionName, ex);
```
* If I was to create my own class to implement `PresentationRepository` how would I set the system so that it gets called when a request is made for a collection? Same for collection.

Thank you,
Petros

**Comment by datazuul** [comment]
better documentation and example-rules will be part of upcoming 4.0.0 release
