### ISSUE TITLE
Full image sizes differ when using TurboJPEG, sizes and tiles properties are missing

### ISSUE THREAD

**Issue by x1rskarw** [dbmdz/iiif-server-hymir#23]
Problem description: full image resolution is not available when using TurboJPEG. 
Expected full image size is 15.000x15.000. Actual full image size is 11.250x11.250.

We're running the current version of hymir built from sources cloned yesterday from git. In addition, we are using TurboJPEG 2.0.0 64bit. The OS is Windows 10.
(Interestingly, we needed to rename the library file from libturbojpeg.dll to turbojpeg.dll and also needed to copy it to the hymir directory in order to get it to work. This might be a naming issue in the Windows version of the TurboJPEG SDK).

We're testing hymir with the file [https://www.nasa.gov/sites/default/files/thumbnails/image/viirs_9apr2015.jpg](https://www.nasa.gov/sites/default/files/thumbnails/image/viirs_9apr2015.jpg) copied to C:/dev/CantaloupePix .  (As you can guess, we are comparing it to Cantaloupe)

Our rules.yaml is trivial:
```
- pattern: ^(.*)$
  substitutions:
    - 'file:/C:/dev/CantaloupePix/$1.jpg'
```

Requesting 
http://127.0.0.1:10000/image/v2/viirs_9apr2015/info.json
we get:
`{"@context":"http://iiif.io/api/image/2/context.json","@id":"http://127.0.0.1:10000/image/v2/viirs_9apr2015","width":11250,"height":11250,"tiles":[{"width":512,"scaleFactors":[1,2,4,8,16]},{"width":1024,"scaleFactors":[1,2,4,8,16]}],"sizes":[{"width":11250,"height":11250},{"width":1875,"height":1875},{"width":2,"height":2}],"profile":["http://iiif.io/api/image/2/level2.json",{"formats":["gif"],"supports":["profileLinkHeader","canonicalLinkHeader","regionSquare","rotationBy90s","mirroring","sizeAboveFull"]}],"protocol":"http://iiif.io/api/image"}`

However, if we disable TurboJPEG by renaming turobjpeg.dll to something else and retry the request we get a different result:
`{"@context":"http://iiif.io/api/image/2/context.json","@id":"http://127.0.0.1:10000/image/v2/viirs_9apr2015","width":15000,"height":15000,"profile":["http://iiif.io/api/image/2/level2.json",{"formats":["gif"],"supports":["profileLinkHeader","canonicalLinkHeader","regionSquare","rotationBy90s","mirroring","sizeAboveFull"]}],"protocol":"http://iiif.io/api/image"}`

The info.json now contains the correct full image width and height but is now missing the size and tiles attributes altogether.

Are these differences intentional? Is there a way to obtain the native performance of TurboJPEG while still retaining the full image size and sites and tiles support?

**Comment by morpheus-87** [comment]
Will be fixed in the upcoming release `4.0.0`.
