### ISSUE TITLE
Upgrading to twelvemonkeys version 3.4.1 introduces problems to TIFF reading

### ISSUE THREAD

**Issue by datazuul** [dbmdz/iiif-server-hymir#29]
When upgrading twelvemonkeys libraries from current version 3.3.2 to 3.4.1 unit tests fail in reading tif image, see example tif 
src/test/resources/mockdata/mock-zoom.tif

**Comment by datazuul** [comment]
I get a "Failed to read JPEG info." IllegalArgumentException when using TwelveMonkeys libraries version 3.4.1 for reading a TIFF with JPEG compressed data.

**Comment by morpheus-87** [comment]
Will be fixed in the upcoming release `4.0.0`.
