### ISSUE TITLE
Tests in error: JpegImageTest.testDownScale:104

### ISSUE THREAD

**Issue by VonUniGE** [dbmdz/iiif-server-hymir#3]
### Observed behavior:
Running `mvn clean install` produces:
```
Tests in error:
  JpegImageTest.testDownScale:104 » UnsatisfiedLink de.digitalcollections.iiif.h...
```
### Desired behavior
No errors in test

### Steps to reproduce
On Debian 8 (Jessie), install libturbojpeg with: 
```
wget https://github.com/dbmdz/iiif-image-api/releases/download/2.2.6/libturbojpeg-jni_1.5.1_amd64.deb
sudo dpkg -i libturbojpeg-jni_1.5.1_amd64.deb
```
Clone the repository with:
```
git clone https://github.com/dbmdz/iiif-server-hymir
```
Run:
```
mvn clean install
```
### Remarks
* This happens in master but not with version 3.0.1 (`git checkout 3.0.1`). Simply because there is no JpegImageTest in 3.0.1.
* java version "1.8.0_121"
* Travis build uses `-DskipTests=true`

**Comment by morpheus-87** [comment]
With the latest version `3.1.0`, that was released yesterday, there is also an updated debian package available, see [here](https://github.com/dbmdz/iiif-server-hymir/releases/tag/3.1.0). If you install this, the compilation should work.

**Comment by VonUniGE** [comment]
Now, I obtain:
```
Tests run: 47, Failures: 0, Errors: 0, Skipped: 0
```
This issue can be closed.

Thank you.

**Comment by morpheus-87** [comment]
Great, thank you very much for your feedback!
