### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by eroux** [dbmdz/iiif-server-hymir#57]
It's been almost 9 months since the latest release and I'm wondering if there is a plan to have a new release soon? Or is there a simple way to use the git version in a spring boot release such as [ours](https://github.com/buda-base/buda-iiif-server/)? Thanks!

**Comment by datazuul** [comment]
We are planning to release this month. The new release has a simplified file resolving backend. For your case (replacing repository with AWS-Backend) it may make replacing simpler. But you may need some help from our side... Short info: New hymir is using new version of digitalcollections-commons-file. See documentation for file resolving here: https://github.com/dbmdz/digitalcollections-commons/tree/master/dc-commons-file#resolved-file-storage

In your case I think you have to overwrite the default implementation and create your own (S3-implementation) class:

de.digitalcollections.commons.file.backend.impl.resolved.ResolvedFileResourceRepositoryImpl

annotated with @Primary to be pulled into Spring context of hymir as default backend...

**Comment by eroux** [comment]
ok, that's good news, thanks! We'll contact you if we have problems

**Comment by datazuul** [comment]
4.0.0 released

**Comment by eroux** [comment]
thanks!
