### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by VonUniGE** [dbmdz/iiif-server-hymir#6]
I've installed Hymir in a cloud virtual machine with 4Gb of memory. I've installled libturbojpeg. I'm serving 129Gb of images. Some images have a size of 4Mb.  These images are scan of books. 

I'm using Mirador to visualize books. Some of them are displayed at a reasonable speed but others are really slow, several minutes to load an image.

I don't know, if it's related to a bug or if it's a configuration issue but I think that `README.md` should give recommendation on:
 - How to correctly choose the `-Xmx` parameter
 - Any advices to improve speed

Thank you.

**Comment by morpheus-87** [comment]
Please describe your runtime environment more detailed:

* which operating system
* what cloud environment (aws?), how does file access work in this cloud (local disc or http access?)

Is there also a performance issue, when you start Hymir on your local machine and access images on your hard disk?

Is loading the full image also slow? (not using Mirador)
Example url: https://api.digitale-sammlungen.de/iiif/image/v2/<identifier>/full/full/0/default.jpg

Regarding runtime parameters, we are using (on a 16GB RAM machine):

`-XX:+ExitOnOutOfMemoryError -XX:+CrashOnOutOfMemoryError -XX:MaxDirectMemorySize=8G -Xmx4G`

We are serving JPG-images up to 100 MB per image. What image format and size/resolution are you reading? Could you please provide us a test image? Is your IIIF-server online accessible?

**Comment by VonUniGE** [comment]
I'm using Debian 8 on a virtual machine (4Gb of memory) hosted by an OpenStack university cloud. Images are JPEG files with an average size of 1Mb and maximum size of 4Mb. Accessing images without hymir is fast. Ther server is not (yet) publicly accessible.

I've migrated the hymir server to another server (outside the cloud) with 12Gb memory and everything is fast.
