### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by jsbien** [dbmdz/iiif-server-hymir#72]
There is a typo in https://github.com/dbmdz/iiif-server-hymir#custom-configuration-file-applicationyml
Instead of
 ``
java xfv hymir-4.0.0.jar application.yml
 ``
there shoud be
 ``
jar xfv hymir-4.0.0.jar application.yml
 ``

**Comment by morpheus-87** [comment]
Thanks for your issue, it is now fixed.
