### ISSUE TITLE
Error in manifest files should appear in log file

### ISSUE THREAD

**Issue by VonUniGE** [dbmdz/iiif-server-hymir#9]
With the default log levels, if a manifest file contains an error nothing appears in the log.

Step to reproduce:
1) Edit one of your manifest file
2) Change `"@type": "dctypes:Image"` to `"@type": "dctypes:Illustration"`
3) Get the manifest `iiif/presentation/v2/1234567890/manifest`
4) Observe that no error message appears in the log and no manifest is returned.

Desired behavior:
An error message should appear in the log

**Comment by datazuul** [comment]
Manifests that can not be parsed with iiif-apis [https://github.com/dbmdz/iiif-apis](https://github.com/dbmdz/iiif-apis) will log an error message with upcoming 4.0.0 release
